name:                slang
version:             0.1.0.0
github:              "seunguklee/slang"
license:             MIT
author:              "Seunguk Lee"
maintainer:          "lsy931106@gmail.com"
copyright:           "2023 Seunguk Lee"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/seunguklee/slang#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- text
- megaparsec
- parser-combinators
- mtl
- repline
- prettyprinter
- optparse-applicative
- directory
- exceptions

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  slang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slang

tests:
  golden-test:
    main:                Test.hs
    source-dirs:         test/golden
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slang
    - tasty
    - tasty-golden
    - filepath
    - bytestring
  interative-test:
    main:                 Test.hs
    source-dirs:          test/interative
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slang
    - tasty
    - tasty-hspec
    - hspec
  parser-test:
    main:                 Test.hs
    source-dirs:          test/parser
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slang
    - tasty
    - tasty-hspec
    - hspec
  typeinfer-test:
    main:                 Test.hs
    source-dirs:          test/typeinfer
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slang
    - tasty
    - tasty-hspec
    - hspec
